# Generated by Django 3.2.4 on 2021-06-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210620_1733'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table='tipo',
        ),
    ]
