# Generated by Django 3.2.4 on 2021-06-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='categ',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
