# Generated by Django 3.2.4 on 2021-06-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_desc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
