# Generated by Django 3.2.4 on 2021-06-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_pvp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pvp',
            new_name='price_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='price_sale',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=9),
        ),
    ]
