# Generated by Django 3.2.4 on 2021-06-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sexo',
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='client',
            name='rut',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Rut'),
            preserve_default=False,
        ),
    ]
