# Generated by Django 3.2.4 on 2021-06-29 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210629_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='supp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
