# Generated by Django 3.2.4 on 2021-06-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_lote_supp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='rut',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Rut'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
