# Generated by Django 3.2.4 on 2021-06-29 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210629_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
