# Generated by Django 3.2.4 on 2021-06-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_supplier_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ini', models.DateField()),
                ('date_end', models.DateField()),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Total')),
                ('payment', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Abono')),
                ('state', models.BooleanField(default=True)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Fiado',
                'verbose_name_plural': 'Fiados',
                'db_table': 'fiado',
                'ordering': ['id'],
            },
        ),
    ]
