# Generated by Django 3.2.4 on 2021-06-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_credited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credited',
            name='date_end',
            field=models.DateField(verbose_name='Fecha Termino'),
        ),
        migrations.AlterField(
            model_name='credited',
            name='date_ini',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
    ]
