# Generated by Django 3.2.4 on 2021-06-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210630_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credited',
            name='cli',
        ),
    ]
