# Generated by Django 3.2.4 on 2021-07-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_credited_cli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credited',
            name='payment',
            field=models.IntegerField(default=0, verbose_name='Abono'),
        ),
        migrations.AlterField(
            model_name='credited',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_cost',
            field=models.IntegerField(default=0, verbose_name='Precio Costo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.IntegerField(default=0, verbose_name='precio Venta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
