# Generated by Django 3.2.4 on 2021-07-01 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_detsale_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsale',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sale'),
        ),
    ]
