# Generated by Django 3.2.4 on 2021-07-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_detsale_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='credited',
            name='cli',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
