# Generated by Django 3.2.4 on 2021-07-05 19:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_credited_cli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credited',
            name='date_ini',
        ),
        migrations.AddField(
            model_name='credited',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='credited',
            name='cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Cliente'),
        ),
    ]
