# Generated by Django 3.2.4 on 2021-07-06 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credited',
            name='state',
        ),
    ]
