# Generated by Django 3.2.4 on 2021-07-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_credited_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='credited',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
