# Generated by Django 3.2.4 on 2021-07-06 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_credited_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credited',
            name='date_end',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha Termino'),
        ),
    ]
