# Generated by Django 3.2.4 on 2021-07-06 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_credited_date_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='supp',
        ),
        migrations.AddField(
            model_name='lote',
            name='prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(default=1, max_length=150, verbose_name='Correo'),
            preserve_default=False,
        ),
    ]
